services:
  backend:
    build: ./backend
    init: true
    ports:
      - 9000:9000
    env_file:
      - .env
    environment:
      - APPID=${OPENWEATHER_API_KEY}
      - MAP_ENDPOINT=${OPENWEATHER_MAP_ENDPOINT}
      - TARGET_CITY=${OPENWEATHER_TARGET_CITY}
    volumes:
      - ./backend:/app
