services:
  backend:
    container_name: eficode-backend
    image: europe-central2-docker.pkg.dev/eficode-recruitment-2024/containers/backend:latest
    build: ./backend
    init: true
    env_file:
      - .env
    environment:
      - PORT=9000
      - APPID=${OPENWEATHER_API_KEY}
      - MAP_ENDPOINT=${OPENWEATHER_MAP_ENDPOINT}
      - TARGET_CITY=${OPENWEATHER_TARGET_CITY}

  frontend:
    image: europe-central2-docker.pkg.dev/eficode-recruitment-2024/containers/frontend:latest
    build:
      context: ./
      dockerfile: ./frontend/docker/prod/Dockerfile
    init: true
    ports:
      - 80:80
      - 443:443
