services:
  backend:
    build: ./backend
    init: true
    ports:
      - ${BACKEND_PORT}:9000
    env_file:
      - .env
    environment:
      - PORT=${BACKEND_PORT}
      - APPID=${OPENWEATHER_API_KEY}
      - MAP_ENDPOINT=${OPENWEATHER_MAP_ENDPOINT}
      - TARGET_CITY=${OPENWEATHER_TARGET_CITY}
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./
      dockerfile: ./frontend/docker/dev/Dockerfile
    ports:
      - ${FRONTEND_PORT}:8000
    env_file:
      - .env
    environment:
      - PORT=${FRONTEND_PORT}
      - HOST=${FRONTEND_HOST}
      - BACKEND_URL=${FRONTEND_ENDPOINT}
    volumes:
      - ./.env:/usr/src/.env
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
      - ./frontend/index.html:/usr/src/app/index.html

  nginx:
    build:
      context: ./
      dockerfile: ./frontend/docker/prod/Dockerfile
    ports:
      - 8000:80
