services:
  backend:
    build: ./backend
    init: true
    ports:
      - 9000:9000
    env_file:
      - .env
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
    volumes:
      - ./backend:/app
