- name: Deploy the application
  hosts: gce

  tasks:
    - name: Create the application directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/app"
        state: directory
        mode: '0755'

    - name: Copy the application files
      ansible.builtin.copy:
        src: "{{ playbook_dir | dirname | dirname }}/{{ item }}"
        dest: "{{ ansible_env.HOME }}/app"
      loop:
        - backend
        - frontend
        - docker-compose.yaml
        - .env

    - name: Run `docker-compose up`
      community.docker.docker_compose_v2:
        project_src: "{{ ansible_env.HOME }}/app"
        state: present
      register: output

    - name: Show results
      ansible.builtin.debug:
        var: output
